# Generated by Django 5.2.15 on 2026-06-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0008_mediaasset'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mediaasset',
            new_name='datahub_med_dashboa_bd4b6f_idx',
            old_name='datahub_med_dashbo_418dc7_idx',
        ),
        migrations.RenameIndex(
            model_name='mediaasset',
            new_name='datahub_med_entity__83a409_idx',
            old_name='datahub_med_entity__49e420_idx',
        ),
        migrations.RenameIndex(
            model_name='mediaasset',
            new_name='datahub_med_categor_824b2d_idx',
            old_name='datahub_med_categor_1c4d55_idx',
        ),
    ]
